server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-1v3r0ibo0nl5rov4.us.auth0.com/
          audience: https://myapp.com/api

#jwt:
 # secret: qwertyuiopasdfghjklzxcvbnm123456  # Change this to a secure value
